menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/justbilt
    GitHub: https://github.com/justbilt
    Rss: /atom.xml

favicon: /favicon.ico
logo: /avatar.png

# Comment
# e.g disqus: seansun
disqus: justbilt
duoshuo: justbilt

# Analytics
# google-analytics:
ga: UA-69555091-1
# baidu-analytics:
ba: false

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
